module.exports = {
  translation: {
    skillName: process.env.skillName, //new
    welcomePrompt: `السلام عليكم ! `,
    chooseMosquePrompt: `أي مسجد تود أن تختار؟ أقرب المساجد إليك هي: %s. يمكنك اختيار المسجد بقول الرقم المرتبط به.`,
    chooseMosqueByTouchPrompt: " أو يمكنك أيضًا النقر على المسجد الذي تريده على شاشتك.",
    helpPrompt: `إليك الأوامر التي يمكنك استخدامها:\n- متى يكون وقت الصلاة القادم؟\n- يمكنك أيضًا أن تطلب وقت كل صلاة بقول مثلاً "متى تكون الصلاة الرابعة؟" لصلاة المغرب\n- كم من الوقت متبقي للإقامة؟\n- أعطني معلومات عن مسجدي.\n- غير المسجد المفضل لدي.\n- أعطني أوقات الصلاة لهذا اليوم.\n- شغل الأذان.\n- شغل أذان الفجر.\nيمكنك أيضًا استخدام هذه الأوامر في روتينات Alexa. أوامر أخرى ستأتي قريباً إن شاء الله.`,
    stopPrompt: `إلى اللقاء، حفظكم الله!`,
    errorPrompt: `عذرًا، لم أفهم ما قلته. من فضلك أعد المحاولة.`,
    noDataPrompt: `عذرًا، لم أتمكن من العثور على بيانات لهذا الطلب. يرجى المحاولة مرة أخرى.`,
    noCityPrompt: `عذرًا، لم أتمكن من العثور على أي مسجد لهذه المدينة. يرجى المحاولة مرة أخرى.`,
    requestForGeoLocationPrompt: `لاستخدام هذا التطبيق، يجب أن تسمح لي بالوصول إلى موقعك لأتمكن من العثور على المساجد الأقرب إليك. افتح تطبيق Alexa على هاتفك للسماح بذلك.`,
    noAddressPrompt: "يبدو أنك لم تقم بتحديد عنوانك في Alexa. يمكنك القيام بذلك من تطبيق Alexa. سيساعدني ذلك في العثور على المساجد القريبة منك.",
    errorPromptforMosqueList: `عذرًا، لم أتمكن من العثور على أي مسجد MAWAQIT قريب منك.`,
    logoUrl: "https://play-lh.googleusercontent.com/79-OHFiVzGLTSLg_tXcsS3VwxWd9ZAxL4eAt35IgIljERyMkYvAq92m-fgpDsZ-lNA",
    titleForMosqueList: `مساجد ${process.env.skillName}`,
    layoutDirection: "RTL",
    nextPrayerTimeErrorPrompt: `عذرًا، لم أتمكن من العثور على وقت الصلاة القادم لمسجدك. يرجى المحاولة مرة أخرى.`,
    nextPrayerTimePrompt: "في %s، الصلاة القادمة هي %s في %s بعد %s. هل تحتاج شيئاً آخر؟",
    prayerNames: ["<phoneme alphabet=\"ipa\" ph=\"fadʒr\">الفجر</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"duhr\">الظهر</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"ʕa.sˤr\">العصر</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"maɣ.rɪb\">المغرب</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"ʔɪʃaːʔ\">العشاء</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"dʒumʕa\">الجمعة</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"ʕiːd\">العيد</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"ʃu.ruːq\">الشروق</phoneme>"],
    unableToFindMosquePrompt: `عذرًا، لم أتمكن من العثور على المسجد الذي تبحث عنه. من فضلك اختر خيارًا صحيحًا.`,
    mosqueNotRegisteredPrompt: `لم تقم بتسجيل أي مسجد للقيام بهذا الطلب. يرجى تسجيل مسجد أولاً.`,
    mosqueSearchWordPrompt: `في أي مكان تريد البحث عن مسجد؟ يمكنك قول اسم المدينة.`,
    nextPrayerTimeWithNamePrompt: `صلاة %s ستكون في %s بعد %s. `,
    noPrayerTimePrompt: `عذرًا، لا توجد أوقات للصلاة %s في هذا المسجد.`,
    hoursAndMinutesPrompt: "%s ساعات و %s دقائق",
    minutesPrompt: "%s دقائق",
    nextPrayerTimeSpecificPrompt: `في %s، صلاة %s ستكون في %s. هل تريد معرفة شيء آخر؟`,
    shuruqPrompt: `في %s، الشروق سيكون في %s. هل تريد معرفة شيء آخر؟`,
    secondsPrompt: "%s ثواني",
    errorGeoConversionPrompt: `عذرًا، لم أتمكن من تحويل عنوانك إلى إحداثيات جغرافية. يرجى المحاولة مرة أخرى.`,
    nextIqamaTimePrompt: `الإقامة للصلاة القادمة %s ستكون بعد %s.`,
    selectedMosquePrompt: `تم اختيار %s كمسجدك المفضل الآن!`,
    nextPrayerWithoutMosquePrompt: `الصلاة القادمة هي %s في %s بعد %s.`,
    iqamaNotEnabledPrompt: "الأوقات بين الأذان والإقامة غير متاحة من المسجد الخاص بك.",
    mosqueInfoPrompt: "مسجدك هو %s. يقع في %s، على بعد حوالي %s كيلومترات من موقعك. وأيضاً، صلاة الجمعة في %s.",
    mosqueInfoErrorPrompt: "عذرًا، لم أتمكن من العثور على معلومات لمسجدك. يرجى المحاولة مرة أخرى.",
    allIqamaTimesPrompt: "بالنسبة لـ %s، الإقامة ستكون في %s.",
    deleteDataPrompt: `تم حذف بياناتك بنجاح. أعد تشغيل التطبيق لاستخدام ${process.env.skillName}.`,
    okPrompt: "حسنًا.",
    jummaTimePrompt: "صلاة الجمعة ستكون في %s.",
    noJummaTimePrompt: "لا توجد صلاة جمعة في هذا المسجد.",
    none: "لا يوجد",
    thankYouPrompt: `شكرًا لاستخدام ${process.env.skillName} للحصول على أوقات الصلاة الدقيقة لمسجدك المفضل.`,
    globalErrorPrompt: "عذرًا، لم أفهم ما قلته. من فضلك أعد المحاولة.",
    fallbackPrompt: "عذرًا، لم أفهم ما قلته. من فضلك أعد المحاولة.",
    allPrayerTimesPrompt: "الصلاة %s ستكون في %s."
  },
};