module.exports = {
    translation: {
      skillName: process.env.SKILL_NAME,
      welcomePrompt: `Salam Aleykum! `,
      chooseMosquePrompt: `Welche Moschee möchten Sie wählen? Hier sind die nächstgelegenen Moscheen: %s. Um eine zu wählen, sagen Sie deren Nummer`,
      chooseMosqueByTouchPrompt: " oder tippen Sie auf die Moschee Ihrer Wahl auf dem Bildschirm.",
      helpPrompt: `Sie können mich zum Beispiel fragen, wann das dritte Gebet des Tages ist, nach einem Hadith fragen oder den Adhan-Rezitator ändern. Die vollständige Liste der Befehle finden Sie in der Skill-Beschreibung.`,
      stopPrompt: `Auf Wiedersehen, und möge Allah Sie schützen!`,
      errorPrompt: `Entschuldigung, ein Fehler ist aufgetreten. Bitte versuchen Sie es später erneut.`,
      noDataPrompt: `Entschuldigung, ich konnte keine Daten für diese Anfrage finden. Bitte versuchen Sie es erneut.`,
      noCityPrompt: `Entschuldigung, ich konnte keine Moschee in dieser Stadt finden. Bitte versuchen Sie es erneut.`,
      requestForGeoLocationPrompt: `Um Moscheen in Ihrer Nähe zu finden, brauche ich Zugriff auf Ihren Standort. Bitte öffnen Sie die Alexa-App, um die Berechtigung zu erteilen.`,
      noAddressPrompt: `Es scheint, dass Ihre Adresse in Alexa nicht festgelegt ist. Sie können sie in der Alexa-App eintragen, damit ich Moscheen in Ihrer Nähe finden kann.`,
      errorPromptforMosqueList: `Entschuldigung, ich konnte keine MAWAQIT-Moschee in Ihrer Nähe finden. Bitte überprüfen Sie den Standort Ihres Geräts. Derzeit funktioniert die Skill nur, wenn eine Moschee in Ihrer Nähe verfügbar ist.`,
      logoUrl: "https://play-lh.googleusercontent.com/79-OHFiVzGLTSLg_tXcsS3VwxWd9ZAxL4eAt35IgIljERyMkYvAq92m-fgpDsZ-lNA",
      titleForMosqueList: `Moscheen ${process.env.SKILL_NAME}`,
      layoutDirection: "LTR",
      nextPrayerTimeErrorPrompt: `Entschuldigung, ich konnte die Zeit für das nächste Gebet nicht finden. Bitte versuchen Sie es erneut.`,
      nextPrayerTimePrompt: "Um %s ist das nächste Gebet %s, um %s, in %s. ",
      prayerNames: [
        "<sub alias='fadschr'>Fajr</sub>",
        "<sub alias='duhr'>Duhr</sub>",
        "<sub alias='asr'>Asr</sub>",
        "<sub alias='magrib'>Maghrib</sub>",
        "<sub alias='ischa'>Isha</sub>",
        "<sub alias='dschumua'>Jumma</sub>",
        "<sub alias='iid'>Eid</sub>",
        "<sub alias='schuruk'>Shuruq</sub>",
      ],
      unableToFindMosquePrompt: `Entschuldigung, ich konnte die gesuchte Moschee nicht finden. Bitte wählen Sie eine gültige Option.`,
      mosqueNotRegisteredPrompt: `Sie haben noch keine Moschee registriert. Bitte registrieren Sie zuerst eine. `,
      mosqueSearchWordPrompt: `In welcher Stadt möchten Sie eine Moschee suchen?`,
      noPrayerTimePrompt: `Entschuldigung, es gibt keine Gebetszeit für %s in dieser Moschee.`,
      hoursAndMinutesPrompt: "%s Stunden und %s Minuten",
      minutesPrompt: "%s Minuten",
      nextPrayerTimeSpecificPrompt: `Um %s ist das %s-Gebet um %s. Möchten Sie noch etwas wissen?`,
      shuruqPrompt: `Um %s ist <sub alias='schuruk'>Shuruq</sub> um %s. Möchten Sie noch etwas wissen?`,
      secondsPrompt: "%s Sekunden",
      errorGeoConversionPrompt: `Entschuldigung, ich konnte Ihre Adresse nicht in Geokoordinaten umwandeln. Bitte versuchen Sie es erneut.`,
      nextIqamaTimePrompt: `Die Iqama für das nächste Gebet, %s, ist in %s.`,
      selectedMosquePrompt: `Perfekt, %s ist jetzt Ihre Lieblingsmoschee! `,
      nextPrayerWithoutMosquePrompt: `Das nächste Gebet ist %s um %s, in %s.`,
      iqamaNotEnabledPrompt: "Die Zeiten zwischen Adhan und Iqama werden von Ihrer Moschee nicht bereitgestellt.",
      mosqueInfoPrompt: "Ihre Moschee ist %s, in %s gelegen, etwa %s Kilometer von Ihnen entfernt. ",
      mosqueInfoErrorPrompt: "Entschuldigung, ich konnte keine Informationen zu Ihrer Moschee finden. Bitte versuchen Sie es erneut.",
      nextPrayerTimeWithNamePrompt: `Das %s-Gebet ist um %s, in %s. `,
      allIqamaTimesPrompt: "Für %s ist die Iqama um %s. ",
      deleteDataPrompt: `Ihre Daten wurden erfolgreich gelöscht. Starten Sie die Skill neu, um ${process.env.SKILL_NAME} wieder zu nutzen.`,
      okPrompt: "Ok. ",
      jummaTimePrompt: "Außerdem ist das Freitagsgebet, <sub alias='dschumua'>Jumua</sub>, um %s.",
      noJummaTimePrompt: "Es gibt kein <sub alias='dschumua'>Jumua</sub>-Gebet in dieser Moschee.",
      none: "Keine",
      thankYouPrompt: `Danke, dass Sie ${process.env.SKILL_NAME} für die Gebetszeiten Ihrer Moschee nutzen. `,
      globalErrorPrompt: "Entschuldigung, ich habe Sie nicht ganz verstanden. Können Sie es bitte wiederholen?",
      fallbackPrompt: "Entschuldigung, ich habe Sie nicht ganz verstanden. Können Sie es bitte wiederholen?",
      allPrayerTimesPrompt: "%s ist um %s. ",
      doYouNeedAnythingElsePrompt: ` Möchten Sie noch etwas?`,
      adhanReciterPrompt: `Welche Rezitation möchten Sie für den Adhan? Sie können zwischen %s wählen. Um eine zu wählen, sagen Sie deren Nummer`,
      adhanReciterErrorPrompt: `Entschuldigung, ich konnte keine Rezitationen für den Adhan finden. Bitte versuchen Sie es erneut.`,
      adhanReciterSuccessPrompt: `Perfekt, %s ist jetzt Ihre Lieblingsrezitation für den Adhan! `,
      titleForAdhaanReciterList: `Adhan-Rezitatoren`,
      chooseAdhaanByTouchPrompt: "oder tippen Sie auf die Rezitation Ihrer Wahl auf dem Bildschirm.",
      hadithErrorPrompt: `Entschuldigung, ich konnte keinen Hadith finden. Bitte versuchen Sie es erneut.`,
      adhaanErrorPrompt: `Entschuldigung, das Abspielen des Adhans ist derzeit nicht verfügbar. Bitte versuchen Sie es später erneut.`,
      selectMosquePrompt: `Um eine Moschee zu registrieren, sagen Sie „wähle meine Moschee". `,
      unableToResolvePrayerNamePrompt: `Entschuldigung, ich konnte den Namen des Gebets nicht erkennen. Bitte versuchen Sie es erneut.`,
      prayerNamePrompt: "Für welches Gebet möchten Sie eine Benachrichtigung erstellen? Sie können zwischen %s wählen. Sagen Sie die Nummer des Gebets",
      prayerNameTouchPrompt: "oder tippen Sie auf das Gebet Ihrer Wahl auf dem Bildschirm.",
      routineCreatedPrompt: `Perfekt, die Benachrichtigung wurde erfolgreich erstellt! `,
      routineErrorPrompt: "Entschuldigung, beim Erstellen der Benachrichtigung ist ein Fehler aufgetreten. Bitte versuchen Sie es später erneut.",
      routineRejected: "Um eine andere Benachrichtigung zu erstellen, sagen Sie „erstelle eine Benachrichtigung\".",
      routineAlreadyEnabled: "Diese Benachrichtigung ist bereits aktiviert. Um eine andere zu erstellen, sagen Sie „erstelle eine Benachrichtigung\".",
      titleForPrayerTimeList: `Gebetszeiten`,
      invalidPrayerIndexPrompt: `Entschuldigung, die angegebene Nummer ist ungültig. Bitte wählen Sie zwischen 1 und %s.`,
      timezoneErrorPrompt: `Entschuldigung, ich konnte Ihre Zeitzone nicht abrufen. Bitte überprüfen Sie Ihre Standort-Einstellungen in der Alexa-App und versuchen Sie es erneut.`,
      requestRoutinePrompt: "Möchten Sie eine Benachrichtigung für dieses Gebet einrichten?",
      hadithWidgetTitle: "Hadith des Tages",
      hadithWidgetDescription: "Wird geladen...",
      widgetInstallationErrorPrompt: "Entschuldigung, beim Installieren des Widgets ist ein Fehler aufgetreten. Bitte versuchen Sie es später erneut.",
      nextPrayerWithoutMosqueAndTimePrompt: "Das nächste Gebet ist %s um %s.",
      linkAccountPrompt: "Um die Benachrichtigung zu aktivieren, verbinden Sie bitte Ihr Amazon-Konto in der Alexa-App und versuchen Sie es erneut.",
      refreshTokenMissing: "Ihre Konto-Verbindung scheint unvollständig zu sein. Um dies zu beheben, deaktivieren und reaktivieren Sie die Skill in der Alexa-App, verbinden Sie Ihr Amazon-Konto, und führen Sie die Geräteerkennung aus.",
      titleForDeleteRoutineList: "Benachrichtigung löschen",
      deleteRoutineConfirmPrompt: "Sind Sie sicher, dass Sie die Benachrichtigung für %s löschen möchten? ",
      routineDeletedPrompt: "Die Benachrichtigung wurde erfolgreich gelöscht. ",
      noRoutinesPrompt: "Sie haben keine Benachrichtigungen aktiviert. Sagen Sie „erstelle eine Benachrichtigung\", um zu beginnen. ",
      deleteRoutinePrompt: "Welche Benachrichtigung möchten Sie löschen? Sie können zwischen %s wählen. Sagen Sie die Nummer der Benachrichtigung",
      deleteRoutineTouchPrompt:
        "oder tippen Sie auf die Benachrichtigung Ihrer Wahl auf dem Bildschirm.",
      deleteRoutineErrorPrompt: "Entschuldigung, beim Löschen der Benachrichtigung ist ein Fehler aufgetreten. Bitte versuchen Sie es später erneut.",
      allRoutinesEnabled: "Alle Benachrichtigungen sind bereits aktiviert. Um eine zu löschen, sagen Sie „lösche eine Benachrichtigung\".",
      allPrayers: "Alle Gebete",
    },
  };
