module.exports = {
  translation: {
    skillName: process.env.skillName, //new
    welcomePrompt: `Salam Aleykoum! `,
    chooseMosquePrompt: `Which mosque would you like to choose? The nearest mosques are: %s, You can choose by saying the number associated with the mosque `,
    chooseMosqueByTouchPrompt: "or you can also click on the mosque of your choice on your screen.",
    helpPrompt: `Here are the commands you can use:\n- When is the next prayer?\n- You can also ask for the time of each prayer by asking for example "When is the fourth prayer?" for Maghrib\n- How much time is left before the iqama?\n- Give me information about my mosque.\n- Change my favorite mosque.\n- Give me the prayer times for the day.\n- Play the adhan.\n- Play the Fajr adhan.\nThese commands can also be used in your Alexa routines. More commands coming soon inshaAllah.`,
    stopPrompt: `Goodbye, and may Allah protect you!`,
    errorPrompt: `Sorry, I didn't quite understand what you said. Please repeat.`,
    noDataPrompt: `Sorry, I couldn't find any data for this request. Please try again.`,
    noCityPrompt: `Sorry, I couldn't find any mosques in this city. Please try again.`,
    requestForGeoLocationPrompt: `To use this skill, you need to allow me access to your location so I can find the mosques closest to you. Please open the Alexa app on your phone to grant permission.`,
    noAddressPrompt: `It seems you haven't set your address on Alexa. You can do so from the Alexa app. This will allow me to find mosques near you.`,
    errorPromptforMosqueList: `I'm sorry, I couldn't find any MAWAQIT mosques near you.`,
    logoUrl: "https://play-lh.googleusercontent.com/79-OHFiVzGLTSLg_tXcsS3VwxWd9ZAxL4eAt35IgIljERyMkYvAq92m-fgpDsZ-lNA",
    titleForMosqueList: `${process.env.skillName} Mosques`,
    layoutDirection: "LTR",
    nextPrayerTimeErrorPrompt: `Sorry, I couldn't find the time for the next prayer at your mosque. Please try again.`,
    nextPrayerTimePrompt: `At %s, the next prayer is %s at %s in %s. Do you need anything else?`,
    prayerNames: ["<phoneme alphabet=\"ipa\" ph=\"fadʒr\">Fajr</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"duhr\">Dhuhr</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"ʕa.sˤr\">Asr</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"maɣ.rɪb\">Maghrib</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"ʔɪʃaːʔ\">Isha</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"dʒumʕa\">Jumma</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"ʕiːd\">Eid</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"ʃu.ruːq\">Shuruq</phoneme>"],
    unableToFindMosquePrompt: `Sorry, I couldn't find the mosque you are looking for. Please choose a valid option.`,
    mosqueNotRegisteredPrompt: `You have not registered a mosque to make this request. Please register a mosque first. `,
    mosqueSearchWordPrompt: `Which location would you like to search for a mosque? You can say the name of the city.`,
    noPrayerTimePrompt: `Sorry, there is no schedule for %s at this mosque.`,
    hoursAndMinutesPrompt: `%s hours and %s minutes`,
    minutesPrompt: `%s minutes`,
    nextPrayerTimeSpecificPrompt: `At %s, the %s prayer is at %s. Do you need anything else?`,
    shuruqPrompt: `At %s, Shuruq is at %s. Do you need anything else?`,
    secondsPrompt: `%s seconds`,
    errorGeoConversionPrompt: `Sorry, I couldn't convert your address to geolocation. Please try again.`,
    nextIqamaTimePrompt: `The iqama for the next prayer %s is in %s.`,
    selectedMosquePrompt: `Perfect, %s is now your favorite mosque! `,
    nextPrayerWithoutMosquePrompt: `The next prayer is %s at %s in %s.`,
    iqamaNotEnabledPrompt: `The times between the adhan and iqama are not provided by your mosque.`,
    mosqueInfoPrompt: `Your mosque is %s. Located at %s, about %s kilometers from your location. `,
    mosqueInfoErrorPrompt: `Sorry, I couldn't find any information for your mosque, please try again.`,
    nextPrayerTimeWithNamePrompt: `The %s prayer is at %s in %s.`,
    allIqamaTimesPrompt: `For %s, iqama is at %s.`,
    deleteDataPrompt: `Your data has been successfully deleted. Restart the skill to use ${process.env.skillName} again.`,
    okPrompt: `Okay. `,
    jummaTimePrompt: `Additionally, Jumua, the Friday prayer, is at %s.`,
    noJummaTimePrompt: `There is no Jumua prayer at this mosque.`,
    none: `None`,
    thankYouPrompt: `Thank you for using ${process.env.skillName} to get the exact prayer times of your favorite mosque. `,
    globalErrorPrompt: `Sorry, I didn't quite understand what you said. Please repeat.`,
    fallbackPrompt: `Sorry, I didn't quite understand what you said. Please repeat.`,
    allPrayerTimesPrompt: `%s is at %s.`,
    doYouNeedAnythingElsePrompt: ` Do you need anything else?`,
    adhanReciterPrompt: `Which recitation would you like to set as favourite for the adhan? You can choose between %s. You can choose by saying the number associated with the recitation `,
    adhanReciterErrorPrompt: `Sorry, I couldn't find any recitations for the adhan. Please try again.`,
    adhanReciterSuccessPrompt: `Perfect, %s is now your favorite recitation for the adhan! `,
    titleForAdhaanReciterList: `Adhan Reciters`,
    chooseAdhaanByTouchPrompt: "or you can also click on the recitation of your choice on your screen.",
    hadithErrorPrompt: `Sorry, I couldn't find any hadiths. Please try again.`,
    adhaanErrorPrompt: `Sorry, Currently, I don't support playing the adhan. Please try again later.`,
    selectMosquePrompt: `To register a mosque, you can say "select my mosque" or "choose my mosque". `,
    unableToResolvePrayerNamePrompt: `Sorry, I couldn't resolve the prayer name. Please try again.`,
  },
};