module.exports = {
  translation: {
    skillName: process.env.skillName, //new
    welcomePrompt: `¡Salam Aleikum! `,
    chooseMosquePrompt: `¿Qué mezquita deseas elegir? Las mezquitas más cercanas son: %s. Puedes elegir diciendo el número asociado a la mezquita.`,
    chooseMosqueByTouchPrompt: " O también puedes hacer clic en la mezquita de tu elección en tu pantalla.",
    helpPrompt: `Aquí tienes los comandos que puedes usar:\n- ¿Cuándo es la próxima oración?\n- También puedes preguntar la hora de cada oración diciendo, por ejemplo, "¿Cuándo es la cuarta oración?" para el Maghrib\n- ¿Cuánto tiempo queda para el iqama?\n- Dame información sobre mi mezquita.\n- Cambia mi mezquita favorita.\n- Dame los horarios de oración del día.\n- Pon el adhan.\n- Pon el adhan del Fajr.\nEstos comandos también se pueden usar en tus rutinas de Alexa. Muy pronto llegarán más comandos inshaAllah.`,
    stopPrompt: `¡Adiós y que Allah te proteja!`,
    errorPrompt: `Lo siento, no entendí lo que dijiste. Por favor, repite.`,
    noDataPrompt: `Lo siento, no encontré ningún dato para esta solicitud. Por favor, inténtalo de nuevo.`,
    noCityPrompt: `Lo siento, no encontré ninguna mezquita para esta ciudad. Por favor, inténtalo de nuevo.`,
    requestForGeoLocationPrompt: `Para usar la aplicación, debes autorizarme a acceder a tu ubicación para que pueda encontrar las mezquitas más cercanas a ti. Abre la aplicación Alexa en tu teléfono para aceptar, por favor.`,
    noAddressPrompt: `Parece que no has configurado tu dirección en Alexa. Puedes hacerlo desde la aplicación Alexa. Esto me permitirá encontrar las mezquitas cercanas a ti.`,
    errorPromptforMosqueList: `Lo siento, no encontré ninguna mezquita MAWAQIT cerca de ti.`,
    logoUrl: "https://play-lh.googleusercontent.com/79-OHFiVzGLTSLg_tXcsS3VwxWd9ZAxL4eAt35IgIljERyMkYvAq92m-fgpDsZ-lNA",
    titleForMosqueList: `Mezquitas ${process.env.skillName}`,
    layoutDirection: "LTR",
    nextPrayerTimeErrorPrompt: `Lo siento, no pude encontrar la hora de la próxima oración para tu mezquita. Por favor, inténtalo de nuevo.`,
    nextPrayerTimePrompt: "A las %s, la próxima oración es %s a las %s en %s. ¿Necesitas algo más?",
    prayerNames: ["<phoneme alphabet=\"ipa\" ph=\"fadʒr\">Fajr</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"duhr\">Duhr</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"ʕa.sˤr\">Asr</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"maɣ.rɪb\">Maghrib</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"ʔɪʃaːʔ\">Isha</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"dʒumʕa\">Yumuah</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"ʕiːd\">Eid</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"ʃu.ruːq\">Shuruq</phoneme>"],
    unableToFindMosquePrompt: `Lo siento, no pude encontrar la mezquita que estás buscando. Por favor, elige una opción válida.`,
    mosqueNotRegisteredPrompt: `No has registrado ninguna mezquita para hacer esta solicitud. Por favor, registra una mezquita primero.`,
    mosqueSearchWordPrompt: `¿Para qué lugar deseas buscar una mezquita? Puedes decir el nombre de la ciudad.`,
    nextPrayerTimeWithNamePrompt: `La oración de %s es a las %s en %s. `,
    noPrayerTimePrompt: `Lo siento, no hay horarios para %s en esta mezquita.`,
    hoursAndMinutesPrompt: "%s horas y %s minutos",
    minutesPrompt: "%s minutos",
    nextPrayerTimeSpecificPrompt: `A las %s, la oración de %s es a las %s. ¿Te gustaría saber algo más?`,
    shuruqPrompt: `A las %s, el Shuruq es a las %s. ¿Te gustaría saber algo más?`,
    secondsPrompt: "%s segundos",
    errorGeoConversionPrompt: `Lo siento, no pude convertir tu dirección en geolocalización. Por favor, inténtalo de nuevo.`,
    nextIqamaTimePrompt: `El iqama para la próxima oración %s es en %s.`,
    selectedMosquePrompt: `Perfecto, %s es ahora tu mezquita favorita.`,
    nextPrayerWithoutMosquePrompt: `La próxima oración es %s a las %s en %s.`,
    iqamaNotEnabledPrompt: "Los tiempos entre el adhan y el iqama no están proporcionados por tu mezquita.",
    mosqueInfoPrompt: `Tu mezquita es %s. Ubicada en %s, a aproximadamente %s kilómetros de tu ubicación. `,
    mosqueInfoErrorPrompt: "Lo siento, no pude encontrar información para tu mezquita. Por favor, inténtalo de nuevo.",
    allIqamaTimesPrompt: "Para %s, el iqama es a las %s.",
    deleteDataPrompt: `Tus datos han sido eliminados con éxito. Reinicia la aplicación para reutilizar ${process.env.skillName}.`,
    okPrompt: "Ok.",
    jummaTimePrompt: `Además, el Yumuah, la oración del viernes, es a las %s.`,
    noJummaTimePrompt: "No hay oración de Yumuah en esta mezquita.",
    none: "Ninguno",
    thankYouPrompt: `Gracias por usar ${process.env.skillName} para obtener los horarios exactos de oración de tu mezquita favorita.`,
    globalErrorPrompt: "Lo siento, no entendí lo que dijiste. Por favor, repite.",
    fallbackPrompt: "Lo siento, no entendí lo que dijiste. Por favor, repite.",
    allPrayerTimesPrompt: "%s es a las %s."
  },
};