
module.exports = {
  translation: {
    skillName: process.env.skillName, //new
    welcomePrompt: `Salam Aleykoum ! `,
    chooseMosquePrompt: ` Which mosque do you want to choose? The nearest mosques are :  %s. You can choose by saying the number associated to the mosque `,
    chooseMosqueByTouchPrompt: "or you can choose by clicking on the mosque on your screen.",
    helpPrompt: `You can ask me to tell you the time of the next prayer or any other prayer, you can also ask me information on your mosque. I can play adhan and change your favorite mosque.`,
    stopPrompt: `Au revoir et qu'Allah vous préserve !`,
    errorPrompt: `Désolé, je n'ai pas bien compris ce que vous avez dit. Veuillez répéter s'il vous plaît.`,
    noDataPrompt: `Désolé, je n'ai pu trouver aucune donnée pour cette reqûete. Veuillez réessayer s'il vous plaît.`,
    noCityPrompt: `Désolé, je n'ai pu trouver aucune mosuée pour cette ville. Veuillez réessayer s'il vous plaît.`,    
    requestForGeoLocationPrompt: `Thanks for using ${process.env.skillName} to provide you exact prayer times of your mosque. To use our skill, we will need to have access to your location so that we can find the nearest mosques from you. Please open the Alexa app to accept.`,
    noAddressPrompt:
      "Il semble que vous n'avez pas défini votre adresse sur Alexa. Vous pouvez le faire depuis l'application Alexa. Cela me permettra de trouver les mosquées proches de vous.",
    errorPromptforMosqueList: `I have found no mosque near your location. I am sorry but for now, there is no mosque equipped with ${process.env.skillName} around you.`,
    logoUrl:
      "https://play-lh.googleusercontent.com/79-OHFiVzGLTSLg_tXcsS3VwxWd9ZAxL4eAt35IgIljERyMkYvAq92m-fgpDsZ-lNA",
    titleForMosqueList: `Mosquées ${process.env.skillName}`,
    layoutDirection: "LTR",
    nextPrayerTimeErrorPrompt: `Désolé, je n'ai pas pu trouver l'heure de la prochaine prière pour votre mosquée. Veuillez réessayer s'il vous plaît.`,
    nextPrayerTimePrompt: "At %s the next prayer is %s at %s in %s. Do you want something more?",
    prayerNames: ["<phoneme alphabet=\"ipa\" ph=\"fadʒr\">Fajr</phoneme>", " <phoneme alphabet=\"ipa\" ph=\"duhr\">Dohr</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"ʕa.sˤr\">Asr</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"maɣ.rɪb\">Maghrib</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"ʔɪʃaːʔ\">Isha</phoneme>","<phoneme alphabet=\"ipa\" ph=\"dʒumʕa\">Jumma</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"ʕiːd\">Eid</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"ʃu.ruːq\">Shuruq</phoneme>"],
    unableToFindMosquePrompt: `Désolé, je n'ai pas pu trouver la mosquée que vous cherchez. S'il vous plaît, choisissez une option valide.`,
    mosqueNotRegisteredPrompt: `Vous n'avez pas enregistré de mosquée pour faire cette reqûete. Veuillez enregistrer une mosquée d'abord. `,
    mosqueSearchWordPrompt: `Pour quel lieu voulez-vous chercher une mosquée ? Vous pouvez dire le nom de la ville.`,
    nextPrayerTimeWithNamePrompt: `à %s, la prière de %s est à %s dans %s. Voulez-vous savoir autre chose ?`, 
    noPrayerTimePrompt: `Désole, il n'y a pas d'horaire pour %s dans cette mosquée.`,
    hoursAndMinutesPrompt: "%s heures et %s minutes",
    minutesPrompt: "%s minutes",
    nextPrayerTimeSpecificPrompt: `à %s, la prière de %s est à %s. Voulez-vous savoir autre chose ?`,
    shuruqPrompt: `à %s, Shourouk est à %s. Voulez-vous savoir autre chose ?`,
    secondsPrompt: "%s seconds",
    errorGeoConversionPrompt: `Sorry, I couldn't convert the address to geolocation. Please try again.`,
    nextIqamaTimePrompt: `The iqama for the next prayer %s is in %s. `,
    selectedMosquePrompt: `Perfect, %s is now your favorite mosque! `,
    nextPrayerWithoutMosquePrompt: `The next prayer is %s at %s in %s.`,
    iqamaNotEnabledPrompt: "Iqama information is not provided by your mosque.",
    mosqueInfoPrompt: "Your mosque is %s. Located at %s, approximately %s km from your location. The jumua is at %s.",
    mosqueInfoErrorPrompt: "Sorry, I couldn't find the information for your mosque. Please try again.",
    nextPrayerTimeWithNamePrompt: ` %s at %s in %s. `,
    allIqamaTimesPrompt: "For %s, the iqama time is %s. ", 
    deleteDataPrompt: "Your data has been deleted successfully.",
    okPrompt: "Ok. ",
    jummaTimePrompt: "The jumma is at %s.",
    noJummaTimePrompt: "There is no jumma time for this mosque.",
    none: "None",
  },
};
