module.exports = {
  translation: {
    skillName: process.env.skillName, //new
    welcomePrompt: `Salam Aleykoum !`,
    chooseMosquePrompt: `Quale moschea vuoi scegliere? Le moschee più vicine sono: %s. Puoi scegliere pronunciando il numero associato alla moschea.`,
    chooseMosqueByTouchPrompt: " oppure puoi anche cliccare sulla moschea di tua scelta sullo schermo.",
    helpPrompt: `Ecco i comandi che puoi utilizzare:\n- Quando è la prossima preghiera?\n- Puoi anche chiedere l'orario di ogni preghiera chiedendo ad esempio "Quando è la quarta preghiera?" per Maghrib\n- Quanto tempo manca prima dell'iqama?\n- Dammi informazioni sulla mia moschea.\n- Cambia la mia moschea preferita.\n- Dammi gli orari delle preghiere della giornata.\n- Metti l'adhan.\n- Metti l'adhan per il Fajr.\nQuesti comandi possono essere utilizzati nelle tue routine Alexa. Altri comandi arriveranno presto, inshaAllah.`,
    stopPrompt: `Arrivederci e che Allah ti protegga!`,
    errorPrompt: `Mi dispiace, non ho capito bene quello che hai detto. Puoi ripetere per favore?`,
    noDataPrompt: `Mi dispiace, non ho trovato alcun dato per questa richiesta. Riprova per favore.`,
    noCityPrompt: `Mi dispiace, non ho trovato alcuna moschea in questa città. Riprova per favore.`,
    requestForGeoLocationPrompt: `Per usare l'applicazione, devi autorizzarmi ad accedere alla tua posizione per trovare le moschee più vicine. Apri l'app Alexa sul tuo telefono per accettare, per favore.`,
    noAddressPrompt: `Sembra che non hai impostato il tuo indirizzo su Alexa. Puoi farlo dall'app Alexa. Questo mi permetterà di trovare le moschee vicine a te.`,
    errorPromptforMosqueList: `Mi dispiace, non ho trovato nessuna moschea MAWAQIT vicino a te.`,
    logoUrl: "https://play-lh.googleusercontent.com/79-OHFiVzGLTSLg_tXcsS3VwxWd9ZAxL4eAt35IgIljERyMkYvAq92m-fgpDsZ-lNA",
    titleForMosqueList: `Moschee ${process.env.skillName}`,
    layoutDirection: "LTR",
    nextPrayerTimeErrorPrompt: `Mi dispiace, non sono riuscito a trovare l'orario della prossima preghiera per la tua moschea. Riprova per favore.`,
    nextPrayerTimePrompt: "Alle %s la prossima preghiera è %s alle %s tra %s. Vuoi altro?",
    prayerNames: ["<phoneme alphabet=\"ipa\" ph=\"fadʒr\">Fajr</phoneme>", " <phoneme alphabet=\"ipa\" ph=\"duhr\">Duhr</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"ʕa.sˤr\">Asr</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"maɣ.rɪb\">Maghrib</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"ʔɪʃaːʔ\">Isha</phoneme>","<phoneme alphabet=\"ipa\" ph=\"dʒumʕa\">Jumma</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"ʕiːd\">Eid</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"ʃu.ruːq\">Shuruq</phoneme>"],
    unableToFindMosquePrompt: `Mi dispiace, non ho trovato la moschea che stai cercando. Per favore, scegli un'opzione valida.`,
    mosqueNotRegisteredPrompt: `Non hai registrato una moschea per fare questa richiesta. Per favore, registra prima una moschea.`,
    mosqueSearchWordPrompt: `Per quale luogo vuoi cercare una moschea? Puoi dire il nome della città.`,
    noPrayerTimePrompt: `Mi dispiace, non ci sono orari per %s in questa moschea.`,
    hoursAndMinutesPrompt: "%s ore e %s minuti",
    minutesPrompt: "%s minuti",
    nextPrayerTimeSpecificPrompt: `Alle %s, la preghiera di %s è alle %s. Vuoi sapere altro?`,
    shuruqPrompt: `Alle %s, Shuruq è alle %s. Vuoi sapere altro?`,
    secondsPrompt: "%s secondi",
    errorGeoConversionPrompt: `Mi dispiace, non sono riuscito a convertire il tuo indirizzo in geolocalizzazione. Riprova, per favore.`,
    nextIqamaTimePrompt: `L'iqama per la prossima preghiera %s è tra %s.`,
    selectedMosquePrompt: `Perfetto, %s è ora la tua moschea preferita!`,
    nextPrayerWithoutMosquePrompt: `La prossima preghiera è %s alle %s tra %s.`,
    iqamaNotEnabledPrompt: "Gli orari tra adhan e iqama non sono forniti dalla tua moschea.",
    mosqueInfoPrompt: "La tua moschea è %s. Situata a %s, a circa %s chilometri dalla tua posizione. Inoltre, il Jumua, la preghiera del Venerdì, è alle %s.",
    mosqueInfoErrorPrompt: "Mi dispiace, non sono riuscito a trovare informazioni per la tua moschea. Riprova per favore.",
    nextPrayerTimeWithNamePrompt: `La preghiera di %s è alle %s tra %s.`,
    allIqamaTimesPrompt: "Per %s, l'iqama è alle %s.",
    deleteDataPrompt: `I tuoi dati sono stati eliminati correttamente. Riavvia l'applicazione per riutilizzare ${process.env.skillName}.`,
    okPrompt: "Ok.",
    jummaTimePrompt: "Il Jumua, la preghiera del Venerdì, è alle %s.",
    noJummaTimePrompt: "Non c'è preghiera di Jumua in questa moschea.",
    none: "Nessuno",
    thankYouPrompt: `Grazie per aver utilizzato ${process.env.skillName} per ottenere gli orari esatti delle preghiere della tua moschea preferita.`,
    globalErrorPrompt: "Mi dispiace, non ho capito bene quello che hai detto. Puoi ripetere per favore?",
    fallbackPrompt: "Mi dispiace, non ho capito bene quello che hai detto. Puoi ripetere per favore?",
    allPrayerTimesPrompt: "%s è alle %s."
  },
};