module.exports = {
  translation: {
    skillName: process.env.skillName, //new
    welcomePrompt: `Salam Aleykoum! `,
    chooseMosquePrompt: `Welke moskee wil je kiezen? De dichtstbijzijnde moskeeën zijn: %s. Je kunt kiezen door het nummer van de moskee uit te spreken.`,
    chooseMosqueByTouchPrompt: " of je kunt ook op het scherm op de moskee van jouw keuze klikken.",
    helpPrompt: `Dit zijn de commando's die je kunt gebruiken:\n- Wanneer is het volgende gebed?\n- Je kunt ook vragen naar het tijdstip van elk gebed, bijvoorbeeld door te vragen "Wanneer is het vierde gebed?" voor Maghrib\n- Hoeveel tijd is er nog voor de iqama?\n- Geef me informatie over mijn moskee.\n- Verander mijn favoriete moskee.\n- Geef me de gebedstijden van de dag.\n- Speel de adhan af.\n- Speel de adhan van Fajr af.\nDeze commando's kunnen ook worden gebruikt in je Alexa-routines. Meer commando's komen binnenkort, inshaAllah.`,
    stopPrompt: `Tot ziens en moge Allah je beschermen!`,
    errorPrompt: `Sorry, ik heb niet goed begrepen wat je zei. Kun je het alsjeblieft herhalen?`,
    noDataPrompt: `Sorry, ik kon geen gegevens vinden voor dit verzoek. Probeer het alstublieft opnieuw.`,
    noCityPrompt: `Sorry, ik heb geen moskee kunnen vinden in deze stad. Probeer het alstublieft opnieuw.`,
    requestForGeoLocationPrompt: `Om de applicatie te gebruiken, moet je mij toestemming geven om toegang te krijgen tot je locatie, zodat ik de dichtstbijzijnde moskeeën voor je kan vinden. Open de Alexa-app op je telefoon om dit goed te keuren.`,
    noAddressPrompt: `Het lijkt erop dat je geen adres hebt ingesteld in Alexa. Dit kun je doen via de Alexa-app. Dit zal mij helpen de dichtstbijzijnde moskeeën te vinden.`,
    errorPromptforMosqueList: `Het spijt me, ik kon geen MAWAQIT-moskeeën bij jou in de buurt vinden.`,
    logoUrl: "https://play-lh.googleusercontent.com/79-OHFiVzGLTSLg_tXcsS3VwxWd9ZAxL4eAt35IgIljERyMkYvAq92m-fgpDsZ-lNA",
    titleForMosqueList: `Moskeeën ${process.env.skillName}`,
    layoutDirection: "LTR",
    nextPrayerTimeErrorPrompt: `Sorry, ik kon de tijd voor het volgende gebed in jouw moskee niet vinden. Probeer het alstublieft opnieuw.`,
    nextPrayerTimePrompt: "Om %s is het volgende gebed %s om %s over %s. Wil je nog iets anders weten?",
    prayerNames: ["<phoneme alphabet=\"ipa\" ph=\"fadʒr\">Fajr</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"duhr\">Duhr</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"ʕa.sˤr\">Asr</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"maɣ.rɪb\">Maghrib</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"ʔɪʃaːʔ\">Isha</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"dʒumʕa\">Jumma</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"ʕiːd\">Eid</phoneme>", "<phoneme alphabet=\"ipa\" ph=\"ʃu.ruːq\">Shuruq</phoneme>"],
    unableToFindMosquePrompt: `Sorry, ik kon de moskee die je zoekt niet vinden. Kies alsjeblieft een geldige optie.`,
    mosqueNotRegisteredPrompt: `Je hebt geen moskee geregistreerd om dit verzoek te doen. Registreer eerst een moskee.`,
    mosqueSearchWordPrompt: `Voor welke plaats wil je een moskee zoeken? Je kunt de naam van de stad zeggen.`,
    noPrayerTimePrompt: `Sorry, er zijn geen tijden voor %s in deze moskee.`,
    hoursAndMinutesPrompt: "%s uur en %s minuten",
    minutesPrompt: "%s minuten",
    nextPrayerTimeSpecificPrompt: `Om %s, is het gebed van %s om %s. Wil je nog iets anders weten?`,
    shuruqPrompt: `Om %s is Shuruq om %s. Wil je nog iets anders weten?`,
    secondsPrompt: "%s seconden",
    errorGeoConversionPrompt: `Sorry, ik kon je adres niet omzetten naar een geografische locatie. Probeer het alstublieft opnieuw.`,
    nextIqamaTimePrompt: `De iqama voor het volgende gebed %s is over %s.`,
    selectedMosquePrompt: `Perfect, %s is nu je favoriete moskee!`,
    nextPrayerWithoutMosquePrompt: `Het volgende gebed is %s om %s over %s.`,
    iqamaNotEnabledPrompt: "De tijden tussen de adhan en iqama worden niet verstrekt door jouw moskee.",
    mosqueInfoPrompt: "Jouw moskee is %s. Gelegen op %s, ongeveer %s kilometer van je locatie. ",
    mosqueInfoErrorPrompt: "Sorry, ik kon geen informatie vinden over jouw moskee. Probeer het alstublieft opnieuw.",
    nextPrayerTimeWithNamePrompt: `Het gebed van %s is om %s over %s.`,
    allIqamaTimesPrompt: "Voor %s, is de iqama om %s.",
    deleteDataPrompt: `Je gegevens zijn succesvol verwijderd. Start de applicatie opnieuw om ${process.env.skillName} opnieuw te gebruiken.`,
    okPrompt: "Oké. ",
    jummaTimePrompt: "Bovendien is het Jumua-gebed, het vrijdaggebed, om %s.",
    noJummaTimePrompt: "Er is geen Jumua-gebed in deze moskee.",
    none: "Geen",
    thankYouPrompt: `Bedankt voor het gebruik van ${process.env.skillName} om de exacte gebedstijden van jouw favoriete moskee te ontvangen.`,
    globalErrorPrompt: "Sorry, ik heb niet goed begrepen wat je zei. Kun je het alsjeblieft herhalen?",
    fallbackPrompt: "Sorry, ik heb niet goed begrepen wat je zei. Kun je het alsjeblieft herhalen?",
    allPrayerTimesPrompt: "%s is om %s."
  },
};