#!/usr/bin/env node
"use strict";

/**
 * sync-locales.js — clone same-language locale assets from a source locale to
 * its variants.
 *
 * MAWAQIT is a Smart Home / Multi-Capability Skill, so Alexa's "automatic
 * distribution" and "sync locales" features are NOT available to it. Instead we
 * hand-maintain ONE source locale per language and generate the same-language
 * variants from it:
 *   - whole interaction-model files (skill-package/interactionModels/custom/),
 *   - the per-locale fields of skill-package/skill.json,
 *   - the per-locale x-amzn-display-details of each skill-package/tasks/ file,
 *   - the per-locale publishingInformation.locales of each
 *     skill-package/dataStorePackages/<pkg>/manifest.json.
 *
 * Run from the repo root after editing a source locale:
 *   node .ask/sync-locales.js
 *
 * To support new locales, extend LOCALE_MAP (source -> variants). To sync a new
 * per-locale JSON section, add its dotted path to SKILL_LOCALE_PATHS,
 * TASK_LOCALE_PATHS, or DATASTORE_LOCALE_PATHS.
 *
 * Generated interaction-model files carry a top-level `_generated` marker and
 * must never be hand-edited — edit the source locale and re-run this script.
 */

const fs = require("node:fs");
const path = require("node:path");

// Source locale -> same-language variants generated from it.
const LOCALE_MAP = {
  "en-US": ["en-AU", "en-CA", "en-GB", "en-IN"],
  "fr-FR": ["fr-CA"],
};

// Per-locale maps in skill.json whose source entry is cloned onto each variant.
const SKILL_LOCALE_PATHS = [
  "manifest.privacyAndCompliance.locales",
  "manifest.publishingInformation.locales",
];

// Per-locale maps in each skill-package/tasks/*.json file.
const TASK_LOCALE_PATHS = ["info.x-amzn-display-details"];

// Per-locale maps in each skill-package/dataStorePackages/<pkg>/manifest.json.
const DATASTORE_LOCALE_PATHS = ["publishingInformation.locales"];

const ROOT = path.resolve(__dirname, "..");
const PACKAGE_DIR = path.join(ROOT, "skill-package");
const MODELS_DIR = path.join(PACKAGE_DIR, "interactionModels", "custom");
const TASKS_DIR = path.join(PACKAGE_DIR, "tasks");
const DATASTORE_DIR = path.join(PACKAGE_DIR, "dataStorePackages");
const SKILL_JSON = path.join(PACKAGE_DIR, "skill.json");

const NOTICE =
  "AUTO-GENERATED by .ask/sync-locales.js — do not edit by hand. " +
  "Edit the source locale and re-run the script.";

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

function writeJson(file, data) {
  fs.writeFileSync(file, `${JSON.stringify(data, null, 2)}\n`);
}

function deepClone(value) {
  return JSON.parse(JSON.stringify(value));
}

function getByPath(obj, dotted) {
  return dotted
    .split(".")
    .reduce((acc, key) => (acc == null ? acc : acc[key]), obj);
}

// Whole interaction-model files: clone the source file to each variant file.
function syncInteractionModels() {
  const done = [];
  for (const [source, variants] of Object.entries(LOCALE_MAP)) {
    const sourceFile = path.join(MODELS_DIR, `${source}.json`);
    if (!fs.existsSync(sourceFile)) {
      throw new Error(`Source interaction model not found: ${sourceFile}`);
    }
    const model = readJson(sourceFile);
    for (const variant of variants) {
      const generated = {
        _generated: `${NOTICE} Source locale: ${source}.`,
        ...model,
      };
      writeJson(path.join(MODELS_DIR, `${variant}.json`), generated);
      done.push(`${source} -> ${variant}.json`);
    }
  }
  return done;
}

// Per-locale JSON sub-maps: clone the source locale entry onto each variant.
function syncJsonLocaleFields(target) {
  const data = readJson(target.file);
  const done = [];
  for (const dotted of target.paths) {
    const locales = getByPath(data, dotted);
    if (locales == null) {
      console.warn(`  (skip) ${target.label}: no "${dotted}"`);
      continue;
    }
    for (const [source, variants] of Object.entries(LOCALE_MAP)) {
      if (!(source in locales)) {
        throw new Error(
          `Missing source locale "${source}" at ${target.label} -> ${dotted}`,
        );
      }
      for (const variant of variants) {
        locales[variant] = deepClone(locales[source]);
        done.push(`${target.label} ${dotted}.${source} -> ${variant}`);
      }
    }
  }
  writeJson(target.file, data);
  return done;
}

// skill.json, every task definition file, and every dataStore package manifest
// get their locale fields synced.
function jsonLocaleTargets() {
  const targets = [
    { file: SKILL_JSON, label: "skill.json", paths: SKILL_LOCALE_PATHS },
  ];
  if (fs.existsSync(TASKS_DIR)) {
    for (const entry of fs.readdirSync(TASKS_DIR)) {
      if (entry.endsWith(".json")) {
        targets.push({
          file: path.join(TASKS_DIR, entry),
          label: `tasks/${entry}`,
          paths: TASK_LOCALE_PATHS,
        });
      }
    }
  }
  if (fs.existsSync(DATASTORE_DIR)) {
    for (const pkg of fs.readdirSync(DATASTORE_DIR)) {
      const manifest = path.join(DATASTORE_DIR, pkg, "manifest.json");
      if (fs.existsSync(manifest)) {
        targets.push({
          file: manifest,
          label: `dataStorePackages/${pkg}/manifest.json`,
          paths: DATASTORE_LOCALE_PATHS,
        });
      }
    }
  }
  return targets;
}

function main() {
  const models = syncInteractionModels();
  const fields = jsonLocaleTargets().flatMap(syncJsonLocaleFields);

  console.log("Interaction models:");
  models.forEach((line) => console.log(`  ${line}`));
  console.log("JSON locale fields:");
  fields.forEach((line) => console.log(`  ${line}`));
  console.log(
    `\nDone — ${models.length} model file(s), ${fields.length} field clone(s).`,
  );
}

main();
